Repository LifeofAGeek/Interview-Problem-Statements-HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#23 find the perimeter of the island.
  islandPerimeter.java
Labels: hacktoberfest2020

#24 Solution for the Issue #9
  Historical_Clickstream.cpp
Labels: hacktoberfest2020

#26 Median of Data Stream - Heap Solution
  find_median_from_data_stream_heap_solution.cpp
Labels: hacktober-accepted, hacktoberfest accepted

#25 Added LargestRangeInArray.cpp
  LargestRangeInArray.cpp
Labels: hacktober-accepted, hacktoberfest accepted

#27 Median of Data Stream - Fenwick Tree Solution
  find_median_from_data_stream_fenwick_tree_solution.cpp
  find_median_from_data_stream_gnu_pbds_order_statistics_tree_solution.cpp
Labels: hacktober-accepted, hacktoberfest accepted

#32 Longest Subarray Zero Sum - Accolite
  longest_subarray_with_zero_sum.cpp
  shortest_subarray_with_all_unique_elements_of_array.cpp
Labels: hacktober-accepted, hacktoberfest accepted

#35 Finding the peak element in the array in JAVA
  Peak of an array in JAVA
Labels: hacktober-accepted, hacktoberfest accepted

#28 Add files via upload
  Newman–Shanks–Williams prime.cpp
  extra long factorials.cpp
  print even and odd indexed char.cpp
  swapping three numbers.cpp
  transpose of a matrix.cpp
Labels: hacktober-accepted, hacktoberfest accepted

#36 swapping in java without extra variable
  swap without 3rd variable in JAVA
Labels: hacktober-accepted, hacktoberfest accepted, hacktoberfest2020

#37 A program to check if a binary tree is BST or not
  BST_tree_check.cpp
Labels: hacktober-accepted, hacktoberfest accepted, hacktoberfest2020

#39 Added LCP Question
  Empty Document
  Given a sorted dictionary (array of words) of an alien language, find order of characters in the language.
  LongestCommonPrefix.cpp
  Newman–Shanks–Williams prime.cpp
  Solution.txt
  extra long factorials.cpp
  print even and odd indexed char.cpp
  s2.txt
  s3.txt
  swapping three numbers.cpp
  transpose of a matrix.cpp
Labels: hacktober-accepted, hacktoberfest accepted, hacktoberfest2020

#38 fast_expo.java
  fast_expo.java
Labels: hacktober-accepted, hacktoberfest accepted, hacktoberfest2020

#41 Added InversionCount Example
  inversionCount.cpp
Labels: hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2020

#40 complex pattern printing problem
  CPP_hard_pattern.cpp
Labels: hacktoberfest accepted, hacktoberfest-accepted, hacktoberfest2020
